DROP TABLE IF EXISTS IDS;
DROP TABLE IF EXISTS  EMPLOYEE;
DROP TABLE IF EXISTS  DEPARTMENT;


CREATE TABLE IDS (
  TABLE_NAME VARCHAR(20) NOT NULL  PRIMARY KEY ,
  NEXT_ID DECIMAL(30,0) NOT NULL
);

CREATE TABLE EMPLOYEE (
	EMPNO             CHAR(20) NOT NULL,
	EMPNM            VARCHAR(20) NOT NULL,
	BIRTHDATE       VARCHAR(20) NOT NULL,
	TELEPHONE       VARCHAR(20) NOT NULL,
	ADDRESS         VARCHAR(80) NOT NULL,
	JOBLEVEL_CODE   VARCHAR(20), 
	SKILL_CODE      VARCHAR(20),
	PRIMARY KEY(EMPNO)
);

CREATE TABLE DEPARTMENT (
	DEPTNO             CHAR(20) NOT NULL,
	DEPTNM            VARCHAR(20) NOT NULL,
	DEPTLOC       VARCHAR(20) NOT NULL,
	DEPTTEL       VARCHAR(20) NOT NULL,
	PRIMARY KEY(DEPTNO)
);

commit;